package com.csk.mssc.beer.order.service.domain;

public enum BeerOrderEventEnum {

    VALIDATE_ORDER, VALIDATION_SUCCESS, VALIDATION_FAILED,
    ALLOCATION_SUCCESS, ALLOCATION_NO_INVENTORY, ALLOCATION_FAILED,
    BEER_ORDER_PICKED_UP

}
